### PR TITLE
Fix build action

### PR DESCRIPTION
**Pull request by chincheta0815**
I changed the files needed for the build according to the build of bliss-analyser.

Therefore, I just left out the specific ARMv7 run. bliss-analyser does build all ARM in the same way as bliss-mixer now.
Everything else is as it was.

In another commit I updated the debian image to bullseye as it is set in bliss-analyser.

I hope that helps building things.

### CODE REVIEW

**Comment by CDrummond** [comment]
Does this mean armv7 is no longer built? As that is required for older raspberries, AFAIK.

**Comment by chincheta0815** [comment]
So far it is no longer build, yes.
But: As far as I read the build for bliss-analyser it is also not build!? Correct me if I am wrong...

I am not that deep in all that stuff, but the old raspi's are only 32bit and need these "gnueabihf" binaries, the new ones are 64bit and need "aarch64" binaries. Looking into the Dockerfile that builds this dlecan image there is hardly the same used!? --> https://github.com/dlecan/rust-crosscompiler-arm/blob/master/arm/Dockerfile

Another thing that is not yet respected: How about i686? Is there no need for that anymore?

**Comment by chincheta0815** [comment]
Right now I think all necessary parts are build:
- arm-unknown-linux-gnueabihf (should be old 32bit raspis)
- aarch64-unknown-linux-gnu (new 64bit raspi)
- x86_64-unknown-linux-musl (... rest)

Only thing: I cannot test all of them I only have a Raspi 4.

**Comment by CDrummond** [comment]
OK, I'm not sure what the removed line actually did now! But I've performed a build, and all artefacts are there, so looks fine to me.

Thanks again.

**Pull request merged**
