### PR TITLE
Formatting fixes, as well as clippy fixes and cargo update

### PR DESCRIPTION
**Pull request by Polochon-street**
Hi!

I'm bliss' main dev, and I've stumbled upon your mixer, which I found really great compared to most of what I made in bliss (https://github.com/Polochon-street/bliss-rs/blob/master/src/playlist.rs)

I think it would be really nice to integrate your mixer to bliss somehow, and (if you're alright with it!) I'm trying to understand if it's possible to make the mixing code provider-agnostic (https://github.com/CDrummond/bliss-mixer/blob/master/src/api.rs#L199-L483, mostly).
To make it easier to understand, I've ran the formatter + the linter and fixed the linting errors, and I thought I'd just submit a PR so everyone benefits from it. I've also run cargo update :)

Cheers,
Paul

### CODE REVIEW

**Comment by CDrummond** [comment]
Hi Paul! We have conversed before - I raised the CUE file issues on bliss-rs :)

The mixer code is pretty agnostic - its just a simple HTTP API that my LMS code invokes. LMS sends a set of 'seed' tracks and 'genre groups' Nothing about that is specific to any media player.

However, as this code does not use bliss-rs's library feature, and uses its own SQLite database I'm not sure how this can be integrated.

**Comment by Polochon-street** [comment]
Hah, true. Thanks for your work, this mixer looks very nice :)

Thanks for merging, also. I think I will add a default "library database provider" to bliss, as well as this mixing logic, but I am not sure exactly how I'll do it - you'll probably see some activity in bliss' commits soon anyways :smile:

Cheers!

**Comment by CDrummond** [comment]
Does the library, mixer, etc, really belong in bliss-rs and not blissify-rs ?

**Comment by CDrummond** [comment]
I also reverted some of the format changes - as I don't like them. I ran 'cargo fmt' before, and never really liked all its changes.

**Comment by Polochon-street** [comment]
> Does the library, mixer, etc, really belong in bliss-rs and not blissify-rs ?

blissify-rs is just an implementation of bliss for MPD, but ideally, I would have 90% of that logic in bliss-rs (or some bliss-rs-library crate, not sure yet), and the 10% would be glue to make it work for MPD (or another specific provider, like LMS).

This would avoid people having to recode the library and mixing logic for each provider (and also provide good default choice).

> I also reverted some of the format changes - as I don't like them. I ran 'cargo fmt' before, and never really liked all its changes.

No worries. I like running it because it's the "official" styling tool (https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md) and it avoids some discussions by providing a source of truth, but I can understand why you would dislike some changes :)

**Pull request merged**
